import os
from engine.rag_store import DocVectorStore

class MarkdownExporter:
    def __init__(self, db_store: DocVectorStore):
        self.db = db_store

    def export_all(self, output_path: str = "API_REFERENCE.md"):
        """
        Pulls all documentation from ChromaDB and compiles it into a single Markdown file.
        """
        print(f"📄 Fetching all documentation from Vector Database...", flush=True)
        
        # In ChromaDB, we can fetch everything by not specifying an ID or query,
        # but to be safe with limits, we'll fetch the entire collection
        result = self.db.collection.get()
        
        if not result or not result.get('documents'):
            print("⚠️ No documentation found in the database. Run ingestion first.", flush=True)
            return False

        documents = result['documents']
        metadatas = result['metadatas']
        
        print(f"📝 Compiling {len(documents)} units into {output_path}...", flush=True)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# 📚 Project API Reference\n\n")
            f.write("> *This documentation is automatically generated by AI Doc Engine.*\n\n")
            f.write("---\n\n")
            
            for i, doc in enumerate(documents):
                meta = metadatas[i] if metadatas and i < len(metadatas) else {}
                file_name = meta.get("file_path", "Unknown File")
                unit_name = meta.get("name", "Unnamed Unit")
                unit_type = meta.get("unit_type", "Chunk").upper()
                
                f.write(f"## {file_name} -> {unit_name} [{unit_type}]\n\n")
                f.write(f"{doc}\n\n")
                f.write("---\n\n")
                
        print(f"✅ Successfully exported API reference to {output_path}", flush=True)
        return True
